# Generated by Django 4.0.2 on 2022-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50, verbose_name='코인 이름')),
                ('market', models.CharField(max_length=50, verbose_name='거래소')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
