# Generated by Django 4.0.2 on 2022-06-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_coin_crypto_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='kr_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='코인 한글이름'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='price',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='코인 가격'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='market',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='거래소'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='ticker',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='코인 티커'),
        ),
    ]
