# Generated by Django 4.0.2 on 2022-06-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_crypto_kr_name_crypto_price_alter_crypto_market_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto',
        ),
    ]
